### ISSUE TITLE
JS alternative for JSON bit

### ISSUE THREAD

**Issue by verheyenkoen** [report-uri/report-uri-js-demo#1]
I was trying to add this to my Next.js/React application but got stuck at some point, where (probably) babel-eslint doesn't allow the JSON bit (`<script type="text/json" id="csp-report-uri">`) in the code. During "compilation" a syntax error (unexpected token, expected "}") is reported on the colon after "keys" (obviously if you're parsing JSON as JS, there will be dragons).

I was wondering if there's a JS way to configure this bit instead 'cause I can't seem to get around that error?

**Comment by ScottHelme** [comment]
All we do is parse in the JSON so you could manual create the `config` variable with your desired values. That would mean you couldn't use our hosted library though, you'd need to host your own custom copy. 

The appropriate line is here: https://github.com/report-uri/report-uri-js/blob/master/report-uri-js.js#L2

**Comment by donaldboulton** [comment]
Headers at: https://report-uri.github.io/report-uri-js-demo/

OK???

report-uri.github.io/:1 Refused to load the image 'https://report-uri.com/img/logo.svg' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

report-uri.github.io/:1 Failed to load https://scotthelme.report-uri.com/r/d/csp/enforce: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://report-uri.github.io' is therefore not allowed access.

**Comment by ScottHelme** [comment]
Thanks for spotting that, the issue should now be fixed @donaldboulton.
